import { User } from "./User"

export const useri: User[] = [
    {
        Id:' dc4fae17-42f8-4198-da4d-08db20aa1788',
        FirstName:' 1234321',
        LastName:' 123',
        MiddleName:' null',
        FullName:' 1234321 123',
        BirthDate:' null',
        Address:' null',
        City:' null',
        State:' null',
        Phone:' null',
        Mobile:' null',
        Email:' aa@aa.com',
        Gender:' ',
        PictureUri:' null',
        CustomId:' null',
        CustomField1:' null',
        CustomField2:' null',
        CustomField3:' null',
        CustomField4:' null',
        CustomField5:' null',
        CustomField6:' null',
        CustomField7:' null',
        CustomField8:' null',
        CustomField9:' null',
        CustomField10:' null',
        IsTimeAttendanceUser:false,
        IsArchived:false,
        HasUserAccount:false,
        UserAccountId:' null',
        UserName:' null',
        CalculationStartDate:' null',
        CalculationStopDate:' null',
        HasAssignedPin:' null'
    },
    {
        Id:' 1a45099e-2769-417b-0b5d-08db2b6fe211',
        FirstName:' 1234321',
        LastName:' 123',
        MiddleName:' null',
        FullName:' 1234321 123',
        BirthDate:' null',
        Address:' null',
        City:' null',
        State:' null',
        Phone:' null',
        Mobile:' null',
        Email:' joj@icloud.com',
        Gender:' ',
        PictureUri:' null',
        CustomId:' null',
        CustomField1:' null',
        CustomField2:' null',
        CustomField3:' null',
        CustomField4:' null',
        CustomField5:' null',
        CustomField6:' null',
        CustomField7:' null',
        CustomField8:' null',
        CustomField9:' null',
        CustomField10:' null',
        IsTimeAttendanceUser:false,
        IsArchived:false,
        HasUserAccount:false,
        UserAccountId:' null',
        UserName:' null',
        CalculationStartDate:' null',
        CalculationStopDate:' null',
        HasAssignedPin:' null'
    },
    {
        Id:' 618dd9a0-eb6d-4d0a-da4e-08db20aa1788',
        FirstName:' 123123123',
        LastName:' 123123123',
        MiddleName:' null',
        FullName:' 123123123 123123123',
        BirthDate:' null',
        Address:' null',
        City:' null',
        State:' null',
        Phone:' null',
        Mobile:' null',
        Email:' 123@123.de',
        Gender:' ',
        PictureUri:' null',
        CustomId:' null',
        CustomField1:' null',
        CustomField2:' null',
        CustomField3:' null',
        CustomField4:' null',
        CustomField5:' null',
        CustomField6:' null',
        CustomField7:' null',
        CustomField8:' null',
        CustomField9:' null',
        CustomField10:' null',
        IsTimeAttendanceUser:false,
        IsArchived:false,
        HasUserAccount:false,
        UserAccountId:' null',
        UserName:' null',
        CalculationStartDate:' null',
        CalculationStopDate:' null',
        HasAssignedPin:' null'
    },
    {
        Id:' 90c45632-94e4-4323-ed1a-08db2f3cb3fb',
        FirstName:' 123123123123',
        LastName:' 123123123',
        MiddleName:' null',
        FullName:' 123123123123 123123123',
        BirthDate:' null',
        Address:' null',
        City:' null',
        State:' null',
        Phone:' null',
        Mobile:' null',
        Email:' 123123123123',
        Gender:' ',
        PictureUri:' null',
        CustomId:' null',
        CustomField1:' null',
        CustomField2:' null',
        CustomField3:' null',
        CustomField4:' null',
        CustomField5:' null',
        CustomField6:' null',
        CustomField7:' null',
        CustomField8:' null',
        CustomField9:' null',
        CustomField10:' null',
        IsTimeAttendanceUser:false,
        IsArchived:false,
        HasUserAccount:false,
        UserAccountId:' null',
        UserName:' null',
        CalculationStartDate:' null',
        CalculationStopDate:' null',
        HasAssignedPin:' null'
    }
]